export { default as Home } from "./Home";
export { default as About } from "./About";
export { default as Development } from "./Development";
export { default as Joint } from "./Joint";
export { default as PropertyManagementAndLeasing } from "./PropertyManagementAndLeasing";
export { default as Contact } from "./Contact";
export { default as Properties } from "./Properties";
export { default as Dunia } from "./Dunia";
export {default as Ponderay} from "./Ponderay";
export {default as News} from "./News";