export const data = {
    about: [
        "About Us",
        "GVD Commercial Properties, Inc. is a US-based real estate development, investment, and management company founded in 1974 by noted shopping center developer Gerald V. Dicker. GVD is well known for its ability to quickly analyze, fund and close complex transactions, most of which involve prime properties held for long term investment.",
        "An innovator in the retail commercial real estate field for over 35 years, GVD initially specialized in the acquisition, development, redevelopment, and management of shopping centers throughout California, the Southwest, and the Pacific Northwest. Over the years, GVD also accumulated a substantial portfolio of net leased investment properties across the country, and now owns over 100 properties in 18 states, totaling more than 2 Million square feet of buildings. The majority of GVD's assets are managed in-house by a staff of highly trained real estate professionals located in GVD's Orange, California and Spokane, Washington offices.",
        "GVD's properties are generally owned debt-free, generating substantial cash flow each year to invest in new properties, or to reinvest in its existing properties. GVD's fiscal conservatism, limited use of financing, and strong cash position have allowed it to survive and grow during economic downturns that were difficult for most others in the real estate industry to weather.",
        `GVD began as a neighborhood shopping center developer, but by the late 1980's had pioneered the development of the "power center", which combined large promotional tenants such as Costco, Home Depot, IKEA, Toys R Us, theatre multiplexes and other "big-box" users, with restaurants and smaller retail users. GVD was also one of the first to partner with community redevelopment agencies to renovate and re-position out-dated shopping centers and mixed-use projects. Such GVD redevelopment projects include the 95-acre Plaza at Puente Hills in the City of Industry, California, and the 40-acre Fullerton Town Center in Fullerton, California.`,
        "GVD has in-house expertise in all phases of real estate development, including site analysis, government entitlements, construction, financing, leasing, and on-going asset and property management.",
        `Regional and national tenants frequently ask GVD to develop new projects for them, to purchase existing centers in which they are located, and to invest in their sale/leaseback properties. When dealing with GVD, tenants know that they will be treated fairly and that GVD has the financial capabilities, expertise, and staff to complete the transaction.`,
        `GVD develops many of its projects as joint ventures with financially conservative landowners who seek stable cash flow and long term appreciation.`,
        `GVD is sensitive to the wishes and needs of the communities in which it develops.`,
        `Projects`,
        `GVD's newer developments include a 95-acre power center in Victorville, California, comprised of such major users as Lowe's, Kohl's, Wal-Mart, Lane Bryant, Marinello's School of Beauty and Turner's Outdoorsman, and a strong line-up of other retail tenants and restaurants, including Chili's, Applebee's, Original Roadhouse Grill, Mimi's Cafe, Johnny Carino's, El Pollo Loco, Wendy's, Sonic Burger, Starbucks, and Baja Fresh. In nearby Apple Valley, GVD also developed a 40-acre project featuring Lowe's, Stater Bros. and Walgreens, Wells Fargo Bank, Carl's Jr., Del Taco, Sonic Burger and El Pollo Loco.`,
        `Current Projects`,
        `GVD is also actively developing projects in Washington State and in Northern Idaho, recently completing a Kohl's, Starbuck's, Verizon Wireless and Del Taco anchored retail development in Coeur d'Alene, Idaho. GVD's "Ruby Suites", mixed use redevelopment project in Spokane, Washington is comprised of a full city block located within the city's University District. The project includes a suites hotel, a mix of restaurants and retail.`,
        `Also under development by GVD are various projects in Coeur d'Alene. GVD's Ponderay project includes the redevelopment of a former K-Mart anchored shopping center together with Hotel Ruby, Ponderay and a planned mixed use project across the street.`,
        `In addition to its retail and mixed use projects, GVD owns the Red Lion River Inn property in Spokane, Washington, and together with one of its related companies, GVD Hospitality Management Services, Inc., owns and operates hotels in Spokane and North Idaho.`,
    ],
    development: [
        "Retail and Mixed Used Properties",
        "Since the formation of the company, GVD has specialized in developing and acquiring shopping centers throughout the western United States. Originally, GVD’s primary market was California and Arizona.",
        "In the mid-1980’s, GVD was the first developer in the United States to build “power centers” (The Plaza at Puente Hills and Fullerton Town Center) in cooperation with the respective cities’ redevelopment agencies. Currently GVD is developing power centers in Victorville and Apple Valley, California.",
        "In recent years, GVD has expanded its development to the Inland Northwest and is currently active in commercial developments in Washington and Idaho. Recently, GVD completed a Kohl’s anchored shopping center in Coeur d’Alene, Idaho. Currently, GVD is planning a mixed use hotel/retail development in downtown Spokane, Washington. GVD’s professionalism, stability and reputation for completing difficult land development transactions has resulted in the company’s selection by local governments for numerous redevelopment and economic development projects."
    ]
}